alias ls='ls -F --color=always'
alias dir='dir -F --color=always'
alias ll='ls -l'
alias la='ls -a'
alias lal='ls -al'
alias cp='cp -iv'
alias rm='rm'
alias mv='mv -iv'
alias grep='grep --color=auto -in'
alias ..='cd ..'
alias h='history'
alias j="jobs -l"